export enum ReferenceType {
    UnitType = 1,
    PropertyType,
    FloorLevel,
    Wifi,
    FurnishType,
    PublicTransportOption,
    Furnishing,
    Facility,
    UtilityIncluded,
    POIType,
    HouseRule,
    TopFeature,
    RoomType,
    BathroomType,
    GenderRule,
    Bedroom,
    Bathroom,
    LocationLevel,
    PropertyGroupType,
    LocationPropertyType,
    UnitPropertyType,
}
